import Head from 'next/head';
import Image from "next/image";

//images 
import image4 from "../public/Screenshot (150).png";
import image1 from "../public/Screenshot (58).png";
import image2 from "../public/Screenshot (6).png";
import image3 from "../public/Screenshot (62).png";
import profileImage from "../public/google.jpg";
import mobiledeveImage from "../public/mobileappdeve.png";
import uiuxdeveImage from "../public/uiuxdeve.png";
import webdeveImage from "../public/webdeve.png";
//frmaer motion

import { motion } from "framer-motion";


import { BsFillMoonStarsFill } from "react-icons/bs";
//icons
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiOutlineGithub
} from "react-icons/ai";


// hooks
import { useState } from 'react';


export default function Home() {

  //function
  const [darkmode ,setdarkmode] = useState(false);
  const icon = {
    hidden: {
      pathLength: 0,
      fill: "rgba(255, 255, 255, 0)"
    },
    visible: {
      pathLength: 1,
      fill: "rgba(255, 255, 255, 1)"
    }
  }

  return (

    <div className={darkmode ? "dark" :"" }>
      <Head>
        <title>Gihan Sanjeewa </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&family=Roboto:wght@100&display=swap');
        </style>
      </Head>

      <main className="font-poppins bg-yellow-50 min-h-screen px-10 md:px-20 lg:px-40 dark:bg-black ">
        {/*nav and hero  */}

        <section>
          {/*navigation pannel*/}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm md:text-xl dark:text-white ">Gihan Sanjeewa</h1>
            <ul className="flex items-center">
              {/*icon */}
              <li> 
                <BsFillMoonStarsFill className="cursor-pointer text-xl mx-5 dark:text-white"  onClick={()=>setdarkmode(!darkmode)} /> 
              </li>
              <li>
                <a href="https://drive.google.com/file/d/1XZmNmtfTAGnpSo60mBauLRAAsQuxugX2/view?usp=sharing" download={"resume"} className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/**hero section */}

          <div className="text-center px-10">
            <h1 className="text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl lg:mb-4 dark:text-white" >Gihan Sanjeewa</h1>

            <h3 className="text-2xl py-4 md:text-3xl  dark:text-red-500 ">IT Undergraduate</h3>

            <p className="text-sm py-4 text-gray-400 leading-6 max-w-xl mx-auto md:text-md dark:text-white">
              As an undergraduate software engineer, I am a motivated and dedicated
              individual with a passion for coding, problem-solving, and a strong
              inclination towards cybersecurity. I possess strong analytical skills and a
              solid understanding of software development principles. Adaptable and
              eager to learn, I am committed to delivering high-quality solutions that
              meet user needs and drive technological innovation, with a particular
              favouritism towards the fascinating world of cyber security.
            </p>

          </div>

          {/**Social media icons  */}

          <div  className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="https://github.com/GihanSanjeewa">
              <AiOutlineGithub/>
            </a>

            <a href="https://www.linkedin.com/in/gihan-sanjeewa-061652276/">
              <AiFillLinkedin/>
            </a>

            <a href="https://web.facebook.com/profile.php?id=100094107186067">
              <AiFillFacebook/>
            </a>
          </div>

          {/**profile image */}
          <motion.div initial={{opacity:0 , scale:0.5}} animate={{opacity:1 , scale:1}} transition={{duration:1}}>
         
          <div className="m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-80 p-5 mt-20">
          
            <Image src={profileImage} alt="" />
            
          </div>
          </motion.div>

        </section>

        {/**services Section  */}

        <section>
          <div>
            <h2 className="text-5xl py-10 font-bold opacity-60 pt-40 dark:text-white">My Services </h2>
            <p className="text-sm py-2 text-gray-400 leading-6 dark:text-white">
            Welcome to my portfolio! I specialize in mobile application development, web application development, and UI/UX design. 
            With expertise in crafting custom mobile apps for both iOS and Android, 
            I create engaging solutions that cater to your unique needs. In the realm of web application development, 
            I transform concepts into responsive, scalable, and high-performance web solutions. Moreover, 
            my UI/UX development ensures that your digital products are not only functional but also visually captivating and user-friendly. 
            Let's collaborate to bring your ideas to life!
            </p>
          </div>

          {/**services cards  */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            
          <div className="md:flex lg:flex gap-10 mx-auto">
            {/**Card 01  */}
            <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={webdeveImage} alt="" width={100} height={100} className=" inline"/>
              <h2 className="text-2xl font-bold">Web Develoment</h2>
              <p className="text-sm py-2 text-gray-800 leading-6">
              Transform your ideas into powerful web solutions. Our web application development 
              services encompass the entire process, from concept to deployment. We specialize in 
              creating responsive and scalable web applications that deliver seamless user experiences 
              </p>
            </div>
            </motion.div>

            <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
            {/**Card 02  */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={mobiledeveImage} alt="" width={100} height={100} className=" inline"/>
              <h2 className="text-2xl font-bold">Mobile Development</h2>
              <p className="text-sm py-2 text-gray-800 leading-6">
              Elevate your business with custom mobile apps tailored to your specific needs. 
              Whether you're targeting iOS or Android users, we craft intuitive and high-performance 
              mobile applications that engage and delight your audience
              </p>
            </div>
            </motion.div>

            <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
            {/**Card 03  */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={uiuxdeveImage} alt="" width={100} height={100} className=" inline"/>
              <h2 className="text-2xl font-bold">UI/UX Development</h2>
              <p className="text-sm py-2 text-gray-800 leading-6">
              User experience is at the heart of every great product. 
              We design intuitive and visually stunning user interfaces that captivate your users and 
              keep them coming back for more. Our UX development ensures that your digital solutions are not just functional, but a joy to use.
              </p>
            </div>
            </motion.div>
          </div>
          </motion.div>
          
        </section>

        {/**my Work Section */}

        <section>
          <div>
            <h2 className="text-5xl py-10 font-bold opacity-60  dark:text-white">My Works</h2>
            <p className="text-sm py-2 text-gray-400 leading-6 dark:text-white">
            Explore a visual journey through my portfolio of diverse projects. Each image represents a unique challenge and a creative solution. 
            From mobile apps that simplify everyday tasks to web applications that streamline business operations, 
            my work showcases a commitment to innovation and excellence. Take a glimpse into my world of design and development, 
            where every project tells a story of creativity, functionality, and user-centric design.
            </p>
          </div>
          {/**Images for my works */}
          <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap ">
            
            <div className="basis-1/3 flex-1">
            <motion.div whileHover={{scale:1.1 , rotate:3}} whileTap={{scale:0.8, rotate:-10, borderRadius:"100%"}}>
            <Image src={image1} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </motion.div>
            </div>
            
            <div  className="basis-1/3 flex-1">
            <motion.div whileHover={{scale:1.1 , rotate:3}} whileTap={{scale:0.8, rotate:-10, borderRadius:"100%"}}>
              <Image src={image2} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </motion.div>
            </div>
            
            <div className="basis-1/3 flex-1">
            <motion.div whileHover={{scale:1.1 , rotate:3}} whileTap={{scale:0.8, rotate:-10, borderRadius:"100%"}}>
              <Image src={image3} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </motion.div>
            </div>

            <div className="basis-1/3 flex-1">
            <motion.div whileHover={{scale:1.1 , rotate:3}} whileTap={{scale:0.8, rotate:-10, borderRadius:"100%"}}>
              <Image src={image4} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </motion.div>
            </div>

          </div>
        </section>

        {/**Footer Section */}

        <footer className="border-t-2 border-black text-sm  opacity-70 flex flex-col gap-5 items-center justify-center py-10 lg:flex-row lg:items-center dark:border-white">
          <div>
            <h3 className="text-base mb-2 dark:text-white">Contact Me For more Details</h3>
            <p className="opacity-40 dark:text-white">
              further more information you can contact me in Whatsappa, linkedin and my facebook. <br/>
              mobile Number : <a className="text-lg  text-blue-800  opacity-100">+94 768537941</a> <br/>
              Whatsapp Link : <a href=" https://wa.me/qr/D7F74FRKYQVBN1"> https://wa.me/qr/D7F74FRKYQVBN1</a>
            </p>
          </div>

          <div  className="text-5xl flex justify-center gap-16 text-gray-600">

            <a href="https://www.linkedin.com/in/gihan-sanjeewa-061652276/">
              <AiFillLinkedin/>
            </a>

            <a href="https://web.facebook.com/profile.php?id=100094107186067">
              <AiFillFacebook/>
            </a>
          </div>

        </footer>
      </main>
     
    </div>
  )
}
