import Head from 'next/head';
import Image from "next/image";

//images 
import profileImage from "../public/google.jpg";

//icons
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiOutlineGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";

//darkmode hooks
import { useState } from 'react';


export default function Home() {

  //function for darkmode
  const [darkmode,setdarkmode] = useState(false);


  return (
    <div className={darkmode? " dark:" :""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&family=Roboto:wght@100&display=swap');
        </style>
      </Head>

      <main className="font-poppins bg-yellow-50 min-h-screen px-10 md:px-20 lg:px-40 dark:bg-black">
        {/*nav and hero  */}

        <section>
          {/*navigation pannel*/}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm md:text-xl dark:bg-black">Gihan Sanjeewa</h1>
            <ul className="flex items-center">
              {/*icon */}
              <li> 
                <BsFillMoonStarsFill 
                 onClick={()=>setdarkmode(!darkmode)} 
                className="cursor-pointer text-xl mx-5"/> 
              </li>
              <li>
                <a href="https://drive.google.com/file/d/10wyxmsnh6WX9CL6s-0RWbGiWEPmXoYFA/view?usp=sharing" download={"resume"} className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/**hero section */}

          <div className="text-center px-10">
            <h1 className="text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl lg:mb-4">Gihan Sanjeewa</h1>

            <h3 className="text-2xl py-4 md:text-3xl ">Full Stack Web Developer and Software Enginear</h3>

            <p className="text-sm py-4 text-gray-400 leading-6 max-w-xl mx-auto md:text-md ">Lorem ipsum dolor sit amet consectetur adipisicing elit. 
              Autem mollitia eius error cum architecto ut minima obcaecati eos 
              animi ratione quos expedita illo, veritatis recusandae, iure,
               eveniet eaque nemo doloremque?
            </p>

          </div>

          {/**Social media icons  */}

          <div  className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="">
              <AiOutlineGithub/>
            </a>

            <a href="">
              <AiFillLinkedin/>
            </a>

            <a href="">
              <AiFillFacebook/>
            </a>
          </div>

          {/**profile image */}
          <div className="m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-80 p-5 mt-20">
            <Image src={profileImage} alt="" />
          </div>


        </section>

        {/**services Section  */}

        <section>
          <div>
            <h2 className="text-5xl py-10 font-bold opacity-60 pt-40">My Services </h2>
            <p className="text-sm py-2 text-gray-400 leading-6">Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
              Modi laboriosam ullam consectetur deserunt enim ipsum soluta, 
              at porro, veniam, iusto omnis sapiente minus natus ipsa illum 
              eligendi autem perferendis ipsam!
            </p>
          </div>

          {/**services cards  */}

          <div className="md:flex lg:flex gap-10 mx-auto">
            {/**Card 01  */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={profileImage} alt="" width={100} height={100} className=" inline"/>
              <h2 className="text-2xl font-bold">Web Develoment</h2>
              <p className="text-sm py-2 text-gray-800 leading-6">Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
              Modi laboriosam ullam consectetur deserunt 
              </p>
            </div>

            {/**Card 02  */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={profileImage} alt="" width={100} height={100} className=" inline"/>
              <h2 className="text-2xl font-bold">Mobile Development</h2>
              <p className="text-sm py-2 text-gray-800 leading-6">Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
              Modi laboriosam ullam consectetur deserunt 
              </p>
            </div>

            {/**Card 03  */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={profileImage} alt="" width={100} height={100} className=" inline"/>
              <h2 className="text-2xl font-bold">UI/UX Development</h2>
              <p className="text-sm py-2 text-gray-800 leading-6">Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
              Modi laboriosam ullam consectetur deserunt 
              </p>
            </div>
          </div>
        </section>

        {/**my Work Section */}

        <section>
          <div>
            <h2 className="text-5xl py-10 font-bold opacity-60 ">My Works</h2>
            <p className="text-sm py-2 text-gray-400 leading-6">Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
              Modi laboriosam ullam consectetur deserunt enim ipsum soluta, 
              at porro, veniam, iusto omnis sapiente minus natus ipsa illum 
              eligendi autem perferendis ipsam!
            </p>
          </div>
          {/**Images for my works */}
          <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap ">
            
            <div className="basis-1/3 flex-1">
            <Image src={profileImage} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </div>
            
            <div  className="basis-1/3 flex-1">
              <Image src={profileImage} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </div>
            
            <div className="basis-1/3 flex-1">
              <Image src={profileImage} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </div>

            <div className="basis-1/3 flex-1">
              <Image src={profileImage} alt="" layout=" responsive" className="rounded-lg object-cover"/>
            </div>

          </div>
        </section>

        {/**Footer Section */}

        <footer className="border-t-2 border-black text-sm  opacity-70 flex flex-col gap-5 items-center justify-center py-10 lg:flex-row lg:items-center">
          <div>
            <h3 className="text-base mb-2">Contact Me For more Details</h3>
            <p className="opacity-40">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
              Aut similique rerum et dignissimos obcaecati natus nostrum 
              harum quasi! Eligendi cum iusto, tempora maxime accusamus 
              explicabo sequi suscipit impedit officiis perferendis.
            </p>
          </div>

          <div  className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="">
              <AiOutlineGithub/>
            </a>

            <a href="">
              <AiFillLinkedin/>
            </a>

            <a href="">
              <AiFillFacebook/>
            </a>
          </div>

        </footer>
      </main>
     
    </div>
  )
}
